### ISSUE TITLE
Error while loading MOTD

### ISSUE THREAD

**Issue by greendoescode** [Spicord/DiscordMOTD#1]
I get this error: 

```
[01:11:42 ERROR] [Spicord]: [JDA:JDA] One of the EventListeners had an uncaught exception
[01:11:42 ERROR]: org.mozilla.javascript.EcmaError: TypeError: Cannot call property of in object [JavaPackage net.dv8tion.jda.core.entities.Game]. It is not a function, it is "object". (Status.js#14)
[01:11:42 ERROR]:       at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4236)
[01:11:42 ERROR]:       at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4214)
[01:11:42 ERROR]:       at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4247)
[01:11:42 ERROR]:       at org.mozilla.javascript.ScriptRuntime.typeError3(ScriptRuntime.java:4273)
[01:11:42 ERROR]:       at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4341)
[01:11:42 ERROR]:       at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2564)
[01:11:42 ERROR]:       at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2546)
[01:11:42 ERROR]:       at org.mozilla.javascript.gen.Status_js_6._c_build_3(Status.js:14)
[01:11:42 ERROR]:       at org.mozilla.javascript.gen.Status_js_6.call(Status.js)
[01:11:42 ERROR]:       at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:98)
[01:11:42 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4._c_next_2(DiscordMOTD.js:37)
[01:11:42 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4.call(DiscordMOTD.js)
[01:11:42 ERROR]:       at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:87)
[01:11:42 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4._c_start_3(DiscordMOTD.js:45)
[01:11:42 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4.call(DiscordMOTD.js)
[01:11:42 ERROR]:       at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:87)
[01:11:42 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4._c_anonymous_1(DiscordMOTD.js:30)
[01:11:42 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4.call(DiscordMOTD.js)
[01:11:42 ERROR]:       at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
[01:11:42 ERROR]:       at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
[01:11:42 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4.call(DiscordMOTD.js)
[01:11:42 ERROR]:       at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
[01:11:42 ERROR]:       at org.spicord.script.RhinoScriptEngine.callFunction(RhinoScriptEngine.java:72)
[01:11:42 ERROR]:       at org.spicord.api.addon.JavaScriptAddon.call(JavaScriptAddon.java:85)
[01:11:42 ERROR]:       at org.spicord.api.addon.JavaScriptAddon.onReady(JavaScriptAddon.java:57)
[01:11:42 ERROR]:       at org.spicord.bot.DiscordBot.lambda$onReady$0(DiscordBot.java:132)
[01:11:42 ERROR]:       at java.base/java.util.ArrayList.forEach(Unknown Source)
[01:11:42 ERROR]:       at org.spicord.bot.DiscordBot.onReady(DiscordBot.java:132)
[01:11:42 ERROR]:       at org.spicord.bot.DiscordBot$BotStatusListener.onReady(DiscordBot.java:306)
[01:11:42 ERROR]:       at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:435)
[01:11:42 ERROR]:       at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.ready(WebSocketClient.java:201)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupController.checkReady(GuildSetupController.java:115)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupController.ready(GuildSetupController.java:102)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupNode.completeSetup(GuildSetupNode.java:375)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupNode.handleMemberChunk(GuildSetupNode.java:258)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupNode.ensureMembers(GuildSetupNode.java:392)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupNode.handleCreate(GuildSetupNode.java:218)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupController.onCreate(GuildSetupController.java:170)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:44)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:956)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:843)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:821)
[01:11:42 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:994)
[01:11:42 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[01:11:42 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[01:11:42 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[01:11:42 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[01:11:42 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
[01:11:42 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[01:11:42 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)

```

while loading the motd package!

I have this in my addons

```
addons = [
    "spicord::info",
    "spicord::players",
    "rewards",
    "staffchat",
    "ban_announcer",
    "chatsync",
    "motd"
  ]
```

Please help, i think this would be very helpful!

**Comment by OopsieWoopsie** [comment]
You are using an outdated build of DiscordMOTD, update it.

**Comment by greendoescode** [comment]
Thats the latest one I can see

**Comment by OopsieWoopsie** [comment]
That's not possible because the latest one uses the net.dv8tion.jda.**api**.entities.Game class, not the net.dv8tion.jda.**core**.entities.Game class (note the api-core difference)

**Comment by greendoescode** [comment]
Ohh, you need to download the one not from releases  sorry

**Comment by OopsieWoopsie** [comment]
No problem! the one at the releases is not a build, is a zip file created by GitHub itself

**Comment by greendoescode** [comment]
Wait can I have a discord link invite?

**Comment by OopsieWoopsie** [comment]
(You need to download the DiscordMOTD.sp file)

**Comment by OopsieWoopsie** [comment]
> Wait can I have a discord link invite?

Sorry but there's no Discord server for support or related.

**Comment by greendoescode** [comment]
Oh
anyways i get this error now

```
[01:49:01 ERROR] [Spicord]: [JDA:JDA] One of the EventListeners had an uncaught exception
[01:49:01 ERROR]: org.mozilla.javascript.EcmaError: TypeError: Cannot call property of in object [JavaPackage net.dv8tion.jda.api.entities.Game]. It is not a function, it is "object". (Status.js#14)
[01:49:01 ERROR]:       at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4236)
[01:49:01 ERROR]:       at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4214)
[01:49:01 ERROR]:       at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4247)
[01:49:01 ERROR]:       at org.mozilla.javascript.ScriptRuntime.typeError3(ScriptRuntime.java:4273)
[01:49:01 ERROR]:       at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4341)
[01:49:01 ERROR]:       at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2564)
[01:49:01 ERROR]:       at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2546)
[01:49:01 ERROR]:       at org.mozilla.javascript.gen.Status_js_6._c_build_3(Status.js:14)
[01:49:01 ERROR]:       at org.mozilla.javascript.gen.Status_js_6.call(Status.js)
[01:49:01 ERROR]:       at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:98)
[01:49:01 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4._c_next_2(DiscordMOTD.js:37)
[01:49:01 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4.call(DiscordMOTD.js)
[01:49:01 ERROR]:       at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:87)
[01:49:01 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4._c_start_3(DiscordMOTD.js:45)
[01:49:01 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4.call(DiscordMOTD.js)
[01:49:01 ERROR]:       at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:87)
[01:49:01 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4._c_anonymous_1(DiscordMOTD.js:30)
[01:49:01 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4.call(DiscordMOTD.js)
[01:49:01 ERROR]:       at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
[01:49:01 ERROR]:       at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
[01:49:01 ERROR]:       at org.mozilla.javascript.gen.DiscordMOTD_js_4.call(DiscordMOTD.js)
[01:49:01 ERROR]:       at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
[01:49:01 ERROR]:       at org.spicord.script.RhinoScriptEngine.callFunction(RhinoScriptEngine.java:72)
[01:49:01 ERROR]:       at org.spicord.api.addon.JavaScriptAddon.call(JavaScriptAddon.java:85)
[01:49:01 ERROR]:       at org.spicord.api.addon.JavaScriptAddon.onReady(JavaScriptAddon.java:57)
[01:49:01 ERROR]:       at org.spicord.bot.DiscordBot.lambda$onReady$0(DiscordBot.java:132)
[01:49:01 ERROR]:       at java.base/java.util.ArrayList.forEach(Unknown Source)
[01:49:01 ERROR]:       at org.spicord.bot.DiscordBot.onReady(DiscordBot.java:132)
[01:49:01 ERROR]:       at org.spicord.bot.DiscordBot$BotStatusListener.onReady(DiscordBot.java:306)
[01:49:01 ERROR]:       at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:435)
[01:49:01 ERROR]:       at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:149)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.ready(WebSocketClient.java:201)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupController.checkReady(GuildSetupController.java:115)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupController.ready(GuildSetupController.java:102)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupNode.completeSetup(GuildSetupNode.java:375)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupNode.handleMemberChunk(GuildSetupNode.java:258)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupNode.ensureMembers(GuildSetupNode.java:392)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupNode.handleCreate(GuildSetupNode.java:218)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.handle.GuildSetupController.onCreate(GuildSetupController.java:170)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:44)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:956)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:843)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:821)
[01:49:01 ERROR]:       at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:994)
[01:49:01 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[01:49:01 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[01:49:01 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[01:49:01 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[01:49:01 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
[01:49:01 ERROR]:       at net.dv8tion.jda.shaded.com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[01:49:01 ERROR]:       at
```

**Comment by OopsieWoopsie** [comment]
I will look at it

**Comment by greendoescode** [comment]
Ok!

**Comment by OopsieWoopsie** [comment]
Confirmed the issue, the Game class does not exist in that package on JDA 4, will work on this now :)

**Comment by greendoescode** [comment]
Ok!

**Comment by greendoescode** [comment]
do you have a disord account though? I would like to message some things

**Comment by OopsieWoopsie** [comment]
> do you have a disord account though? I would like to message some things

Sorry but my Discord is not public. 
I have uploaded a new build, it is supposed to work now :)

Edit: If you send me your discord # I can then send you a friend request.

**Comment by greendoescode** [comment]
Ok one sec
